### ISSUE TITLE
Does it makes sense to use wyvox/setup-action-pnpm?

### ISSUE THREAD

**Issue by NullVoxPopuli** [embroider-build/release-plan#44]
So, setup-action-pnpm is a meta action, which doesn't really do anything special other than try to interpret the package.json correctly.

For example:
![image](https://github.com/embroider-build/release-plan/assets/199018/9f093860-d30c-417f-a694-d9dfe5a8a18a)

When I tried to setup release-plan on ember-sortable, I was getting errors, because it assumed pnpm 8 -- and like, _some file_ should teh source of truth for that sort of thing (package.json#packageManager is a good such source)

thoughts?

-----

here is the then-resulting upgrade to pnpm-8 to fix release-plan: https://github.com/adopted-ember-addons/ember-sortable/pull/534
(note: volta not used on CI, only some folks' machines)

----

Here is a preview of what release-plan using wyvox/setup-action-pnpm would look like: 
https://github.com/adopted-ember-addons/ember-sortable/pull/535

I think one potential blocking feature that would need to be implemented is a fallback for node version lookup (in action/setup-node) -- I've configured it to look in package.json -- but ~~I don't (yet) know if action/setup-node will continue looking other places if not found~~ -- for example -- in the embroider repo, [`use-node-version`](https://github.com/embroider-build/embroider/blob/2a6775b229761c0f745c67f536002256a71b2f1c/.npmrc#L2) is specified in the `.npmrc`.

We'll need to PR to here: https://github.com/actions/setup-node/blob/b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8/src/main.ts#L82
to add support for the `.npmrc` property that pnpm is looking for

**Comment by mansona** [comment]
I'd very much like to not do this. I find it a lot clearer to just have standard things in github actions, and with some of the pushback I've had about using it in ember-cli I'd rather not introduce it here 👍
