### ISSUE TITLE
Breaks upon switching .npmrc (in a pnpm monorepo) to ues shared-workspace-lockfile=false

### ISSUE THREAD

**Issue by NullVoxPopuli** [embroider-build/release-plan#46]
https://pnpm.io/npmrc#shared-workspace-lockfile

The reason I needed this was for extreme isolation between workspaces.

The actual problem is with `@ef4/lerna-changelog`, but I wonder if we should just move that code into release-plan?

Here is the code that errors, (due to not-quite-json)
```
❯ pnpm m ls --json --depth=-1
[
  {
    "path": "/home/nvp/Development/NullVoxPopuli/ember-resources-2",
    "private": true
  }
]
[
  {
    "name": "@nullvoxpopuli/estimate-bytes",
    "path": "/home/nvp/Development/NullVoxPopuli/ember-resources-2/dev/estimate-bytes",
    "private": true
  }
]
[
  {
    "name": "docs",
    "version": "0.0.0",
    "path": "/home/nvp/Development/NullVoxPopuli/ember-resources-2/docs",
    "private": true
  }
]
[
  {
    "name": "ember-resources",
    "version": "6.5.0",
    "path": "/home/nvp/Development/NullVoxPopuli/ember-resources-2/ember-resources",
    "private": false
  }
]
[
  {
    "name": "test-app",
    "version": "0.0.0",
    "path": "/home/nvp/Development/NullVoxPopuli/ember-resources-2/test-app",
    "private": true
  }
]
[
  {
    "name": "test-app-definitely-typed",
    "version": "0.0.0",
    "path": "/home/nvp/Development/NullVoxPopuli/ember-resources-2/test-app-definitely-typed",
    "private": true
  }
]

```

from:
```
       │ File: /home/nvp/Development/NullVoxPopuli/ember-resources-2/node_modules/.pnpm/@ef4+lerna-changelog@2.0.0/node_modules/@ef4/lerna-changelog/lib/configuration.js
```

As it turns out, this is blocking the release of ember-resources@v7 :sweat_smile: 

https://github.com/NullVoxPopuli/ember-resources/actions/runs/7482171149/job/20365200936

**Comment by mansona** [comment]
This should be fixed in our lerna changelog fork 👍 ... ah it seems like we don't have issues turned on 🙈 I'll chat to @ef4 and see if we can't get it sorted

**Comment by NullVoxPopuli** [comment]
Looks like I have to make the [same change](https://github.com/NullVoxPopuli/ember-resources/pull/1106) in release-plan:

https://github.com/NullVoxPopuli/ember-resources/actions/runs/7491921558/job/20394270983#step:4:29
