### ISSUE TITLE
Publish private package

### ISSUE THREAD

**Issue by saracope** [embroider-build/release-plan#80]
I'd like to publish private packages but I'm not seeing that as an option. Can you clarify if that is possible?

**Comment by mansona** [comment]
can you clarify what you mean by publishing a private package? 🤔 I have a feeling that there is a difference of understanding we might need to bridge before I can answer 😂 

my understanding of "private package" means that you have `private: true` in your package.json and that means you never want it to go to npm ever.

**Comment by saracope** [comment]
Yeah that's the value to keep a package from being published but a [private NPM package](https://docs.npmjs.com/creating-and-publishing-private-packages) is similar to a private GitHub repo in that it is published but only available to users/teams with access to view it. This is set in the [package Config](https://docs.npmjs.com/cli/v10/using-npm/config#config-settings) using 
```
"publishConfig": {
	"access": "restricted"
}
```
or using `pnpm publish --access=restricted`

I think I would need release plan to check that config value and/or accept it in the the publish.yml.

**Comment by mansona** [comment]
hmm... so `release-plan publish` just proxies to pnpm publish if you're using pnpm (or npm if you're just using npm) so if adding stuff to the package.json is the way to configure this then that should just work 🤷

**Comment by saracope** [comment]
With access restricted in the package.json and in the publish.yml it still published as public. Here is some output from a release:

```
Run pnpm release-plan publish --dry-run --access=restricted

 ℹ️ --dryRun active. Skipping `pnpm publish --access=public` for ...
```

It seems to be hard-coded in the [`npm publish` function](https://github.com/embroider-build/release-plan/blob/499ac893e347a23fedd68b6168f3e8651527f708/src/publish.ts#L233).  

Could access be added to [PublishOptions](https://github.com/embroider-build/release-plan/blob/499ac893e347a23fedd68b6168f3e8651527f708/src/publish.ts#L13)?

I can start a PR if exploring this would be ok for you right now.
